# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 533c5c35106dc7140c2666d6d03acd434f111034323462ae035831056540ce3080884a4ba1a6eaf90043a5eed1529228964bd2ad0cacbd474c3b421f054e24f1

test:
  secret_key_base: 18fef66c700d67d466ddd70f9435099ed10e53247e13a7313e63848241a0cd9cd399349ec854ef64485b869fa0282bb3ae7ee482f8054a72a00bc11b459a83fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
